name: Publish to PyPI
on:
  pull_request:
    branches: [main]
  push: 
    branches: [main]
    tags: ["*"]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx install hatch
      
      - name: Build
        run: hatch build
      
      - name: Collect version
        id: collect_version
        run: echo version=$(hatch version) >> $GITHUB_OUTPUT
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.collect_version.outputs.version }}
          path: dist
          retention-days: 1

      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1